### PR TITLE
Slurm robust to no jobid and to node warnings

### LINKED ISSUE #127: Slurm Job creation crashes on master because "SLURM_JOB_ID" not set
In order to get around the replace bug mentioned in  #118  I installed directly from master, but this introduced another bug namely that the .out name change introduced in #123 causes job creation to crash, since it seems that on my cluster  does not seem to set  SLURM_JOB_ID (nor any other slurm variable) at the point in time which the code expects?

Removing the jobID solved the problem.

### PR DESCRIPTION
**Pull request by grahamas**
Resolves #127 

Resolves additional bug where the port and IP info are not parsed when a warning or error from the node (e.g. "TMPDIR could not be created") occupies the first lines of the output file.

Related but unnecessary changes:  I removed "job_" from the output file name.  I stopped the automatic deletion of previous logs.  At the very least, that should have a flag associated with it.

### CODE REVIEW

**Comment by bjarthur** [comment]
are there any slurm users out there who would like to review this PR?

File: src/slurm.jl [hunk 1]
```diff
@@ -50,44 +50,46 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
             mkdir(job_file_loc)
         end
 
-        println("removing old files")
+        # println("removing old files")
```
Comment (kescobo) [inline src/slurm.jl:53]: Should make sure this stuff gets removed from final PR

File: src/slurm.jl [hunk 2]
```diff
@@ -50,44 +50,46 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
...
         # cleanup old files
-	map(f->rm(joinpath(job_file_loc, f)), filter(t -> occursin(r"job(.*?).out", t), readdir(job_file_loc)))
-        println("removing old Setting up srun commands")
+	    # map(f->rm(joinpath(job_file_loc, f)), filter(t -> occursin(r"job(.*?).out", t), readdir(job_file_loc)))
```
Comment (kescobo) [inline src/slurm.jl:55]: Remove here too

File: src/slurm.jl [hunk 3]
```diff
@@ -50,44 +50,46 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
...
+        make_job_output_path(task_num) = joinpath(job_file_loc, "$(job_output_name)-$(task_num).out")
+        job_output_template = make_job_output_path("%4t")
+        srun_cmd = `srun -J $jobname -n $np -o "$(job_output_template)" -D $exehome $(srunargs) $exename $exeflags $(worker_arg())`
         srun_proc = open(srun_cmd)
+        slurm_spec_regex = r"([\w]+):([\d]+)#(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})"
         for i = 0:np - 1
             println("connecting to worker $(i + 1) out of $np")
-            local w=[]
-            fn = "$(joinpath(exehome, job_file_loc))/job-$jobID-$(lpad(i, 4, "0")).out"
+            local slurm_spec_match = nothing
```
Comment (kescobo) [inline src/slurm.jl:67]: Is the `local` keyword necessary? This is inside a function, it should be locally scoped regardless.

File: src/slurm.jl [hunk 4]
```diff
@@ -50,44 +50,46 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
...
+            fn = make_job_output_path(lpad(i, 4, "0"))
             t0 = time()
             while true
```
Comment (kescobo) [inline src/slurm.jl:70]: I'm confused about the need for this loop. It looks like there's no situation where it would actually loop back to the top.

File: src/slurm.jl [hunk 5]
```diff
@@ -50,44 +50,46 @@ function launch(manager::SlurmManager, params::Dict, instances_arr::Array,
...
 
-        println("removing old files")
+        # println("removing old files")
         # cleanup old files
-	map(f->rm(joinpath(job_file_loc, f)), filter(t -> occursin(r"job(.*?).out", t), readdir(job_file_loc)))
-        println("removing old Setting up srun commands")
+	    # map(f->rm(joinpath(job_file_loc, f)), filter(t -> occursin(r"job(.*?).out", t), readdir(job_file_loc)))
 
         np = manager.np
         jobname = "julia-$(getpid())"
```
Comment (kescobo) [inline src/slurm.jl:58]: I wonder if it would be worth making this user-setable, with this as default. Probably beyond the scope of this PR...

**Review by kescobo — APPROVED** [review]
This looks good to me, other than removing the commented out print statements. 

There are also a could of places where it looks like you followed what was there previously, though what was there previously doesn't seem necessary (the `local` and `while` loop). Usually, it's probably best-practice to carry forward previous decisions unless the PR is specifically meant to address them, but since this code is pretty old, and you've just been elbow deep in it, might be worth taking a look at.

File: src/slurm.jl (hunk 5 above)
Comment (grahamas) [reply src/slurm.jl:58]: I was thinking that, too.  I could expose that functionality from `launch`, but I think it would be a separate PR to expose it to the end-user.  Which would be fine, but I think there needs to be some discussion of what form that option would take.  A boolean could be fine, but to really be complete you'd probably want the option to be an anonymous function, like `remove_old_logs=t -> occursin(r"job(.*?).out", t)` maybe with the convenience function that `remove_old_logs=true` uses the function `remove_old_logs=t -> occursin(r"job(.*?).out", t)` by default.  And `remove_old_logs=false` does nothing.  I'll open an issue for this.

Comment (grahamas) [reply src/slurm.jl:58]: Huh. Seems like this wouldn't need to be standardized-- it just flows through the params argument to launch. I'll add it as i described in the previous comment, unless anyone has any objections. (so it'll be a keyword argument to `addprocs_slurm` which will be passed to `launch` via the `params` dict)

File: src/slurm.jl (hunk 4 above)
Comment (grahamas) [reply src/slurm.jl:70]: The log file takes a while to create and might be empty for a split second when it is created. So you have to sit there checking to see if the file has been populated yet before you can parse it for the worker specification, and so that the code doesn't continue until the workers are actually created.

File: src/slurm.jl (hunk 5 above)
Comment (grahamas) [reply src/slurm.jl:50]: In testing this out, I changed my mind.  I'm not comfortable adding this feature in this way because it's not obvious what is meant by an "old" log file.  In particular, if you run `addprocs_slurm` a second time in a single session, with this option set to `true`, it will delete the still-active log files from the first session.  Since it's easy enough to delete them manually, I'd rather not introduce the danger and ambiguity.

**Comment by grahamas** [comment]
@kescobo Thanks for reviewing! If my explanation of that loop makes sense, then I think we're all good.

File: src/slurm.jl (hunk 4 above)
Comment (kescobo) [reply src/slurm.jl:62]: Ahh, got it - can you just add a comment to that effect or something?

**Comment by kescobo** [comment]
Cool :+1: if you could just add a comment to the loop to clarify the point of it? (I know you didn't introduce it, but would be great to document it while it's top of mind). Then this is ready to merge AFAIC

**Comment by grahamas** [comment]
Comments added!  Plus a few more.
