### PR TITLE
Some PBS clusters have different stdoutput files

### LINKED ISSUE #85: Jobfile is incorrect on some PBS clusters
When I submit an array job to the cluster with a command:
```
qsub -N test -j oe -k o -t 1:5 ./test
```
I get list of log files in a form
```
test-1.o50084
test-2.o50084
test-3.o50084
test-4.o50084
test-5.o50084
```
which is different from logfile form ClusterManagers is now looking namely - <job name>.o<id>-<i>. In cluster I have access `qsub --version` is 4.2.10. Seems until 6.0.0 output schematics had changed as can be seen in [this](https://github.com/JuliaParallel/ClusterManagers.jl/pull/47) issue. But seems this specific detail is undocumented. 

When changing schematics manually in qsub.jl cluster worked fine. Thus this might be an annoying bug for newcomers with an easy fix. For example filename(i) could return a list of files which would be checked in the loop or there could be another condition which decide the schematics of filenames depending on `qsub` version.

### PR DESCRIPTION
**Pull request by akels**
Some PBS clusters have different schematics for standard output files when array jobs are used. This fixes #85 .

### CODE REVIEW

File: src/qsub.jl [hunk 1]
```diff
@@ -81,15 +81,19 @@ function launch(manager::Union{PBSManager, SGEManager, QRSHManager},
...
+            filenames(i) = "$home/julia-$(getpid()).o$id-$i","$home/julia-$(getpid())-$i.o$id","$home/julia-$(getpid()).o$id.$i"
+            
             print("job id is $id, waiting for job to start ")
             for i=1:np
                 # wait for each output stream file to get created
-                fname = filename(i)
-                while !isfile(fname)
+                fnames = filenames(i)
+                j = 0
+                while (j=findfirst(x->isfile(x),fnames))==0
```
Comment (vchuravy) [inline src/qsub.jl]: I prefer having the condition be a simple `j==0` and do the update within the loop. IMO that reads a bit clearer, but nothing that should hold this up.

Comment (akels) [reply src/qsub.jl]: Thanks :)
